---
title: "Final Project"
author: "Georgianna Fischer"
date: "2023-11-21"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data Cleaning

```{r data cleaning, include=FALSE}
if (interactive()) {
  chloride_raw <- read.csv(file.choose())
} else {
  chloride_raw <- read.csv("Chloride_ogR.csv")
}


chloride_data <- chloride_raw %>% 
        rename( "n_overall" = "n..overall.Cl.avg.",
              "Overall_avg_Cl" = "Overall.Cl.Avg...mg.L.",
               "n_summer_overall" = "n..overall.summer.Cl.avg.",
                "summer_overall_avg_cl" = "Overall.Summer.Cl.Avg...mg.L.",
               "n_recent_overall" = "n..recent.cl.avg.",
               "recent_avg_cl" = "Recent.Cl.Avg...mg.L.",
               "n_recent_summer_overall" = "n..recent.summer.cl.avg.",
               "summer_recent_avg_cl" = "Recent.Summer.Cl.Avg...mg.L.",
               "no_yrs" = "no..yrs.data")
chloride_data %>% drop_na(summer_overall_avg_cl)

if (interactive()) {
  SURF_raw <- read.csv(file.choose())
} else {
  SURF_raw <- read.csv("SURFdata.csv")
}
SURF_data <- subset(SURF_raw, select = -c(X, X.1, X.2, X.3, X.4))
```

## Historical Graph

```{r Historic Patterns, include=FALSE}
chloride_sum <- chloride_data %>%
  drop_na(summer_overall_avg_cl) %>%
  group_by(type) %>%
  summarize(mean_Overall_avg_Cl = mean(Overall_avg_Cl), mean_summer_overall_cl = mean(summer_overall_avg_cl), mean_recent_cl = mean(recent_avg_cl), mean_recent_summer_cl = mean(summer_recent_avg_cl))

Avg_summer_plot <- chloride_sum %>%
  ggplot(aes(x = type, y = mean_summer_overall_cl)) + 
  geom_bar(stat = 'identity', fill = 'lightblue') +
  labs(title = "Historical (1969-2022) Average Summer Chloride by Type", 
       x = "Waterbody Type", 
       y = "Mean summer chloride (mg/L)") + 
  theme_minimal()
print(Avg_summer_plot)
```
## Historical Analysis
The results of the historical summer chloride graph shows a lot of variance between the types of water bodies. The lowest average chloride values lie in ponds and mixed wetlands and ponds, 

## Recent graphs

```{r recent patterns graphs}
SURF_data <- SURF_data %>%
  mutate(typeWater = ifelse(X18O > -7, "surface", "ground"))

O18_plot <- ggplot(data = SURF_data, aes(x = Cl, y = X18O)) + 
  geom_point() + 
  geom_smooth(method = "lm", color = "blue") +
  labs(x = "Chloride (mg/l)", y = "18O")+
  theme_minimal()

Rd_length_plot <- ggplot(data = SURF_data, aes(x = Cl, y = RdLength_per_WtshdArea, color = typeWater)) + 
  geom_point() + 
  geom_smooth(method = "lm", color = "red") +
  labs(x = "Chloride (mg/l)", y = "Road Length 
       per Watershed Area") +
  guides(color = guide_legend(title = "Dominant Water Source")) +
  theme_minimal() +
  theme(legend.position = "bottom") 


wtshd_dev_plot <- ggplot(data = SURF_data, aes(x = Cl, y = Percent_wtshd_dev, color = typeWater)) + 
  geom_point() + 
  geom_smooth(method = "lm", color = "red") +
  labs(x = "Chloride (mg/l)", y = "Percent Developed") +
  coord_cartesian(ylim = c(0, 100)) +
  theme_minimal() +
  theme(legend.position = "none")

DIC_plot <- ggplot(data = SURF_data, aes(x = Cl, y = DIC)) + 
  geom_point() + 
  geom_smooth(method = "lm", color = 'blue') +
  labs(x = "Chloride (mg/l)", y = "DIC")+
  theme_minimal()
combined_SURFplots <- O18_plot / DIC_plot / Rd_length_plot / wtshd_dev_plot + plot_layout(ncol = 2)
print(combined_SURFplots)
```

## Recent Linear Regressions

```{r recent patterns linear regressions}
O18_linearmod <- lm(X18O~Cl, data = SURF_data)
summary(O18_linearmod)
DIC_linearmod <- lm(DIC~Cl, data = SURF_data)
summary(DIC_linearmod)
wtshd_dev_linearmod <- lm(Percent_wtshd_dev~Cl, data = SURF_data)
summary(wtshd_dev_linearmod)
roads_linearmod <- lm(RdLength_per_WtshdArea~Cl, data = SURF_data)
summary(roads_linearmod)
```

